server:
#  port: 8002
  port: 8000

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑,ShardingSphereDriver不再是MysqlDriver
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径，里面分库分表的核心配置文件,JVM 参数 -Ddatabase.env= 决定下面的动态参数，默认空为dev
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.dev:dev}.yaml
#    # 使用分表的方式，下面的相关数据库配置替换为上面的shardingsphere的相关配置
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://127.0.0.1:3306/link?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.cj.jdbc.Driver
    # hikari 连接池
#    hikari:
#      connection-test-query: select 1
#      connection-timeout: 20000
#      idle-timeout: 300000
#      maximum-pool-size: 5
#      minimum-idle: 5
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      # password:

short-link:
  group:
    max-num: 20
  # 流量控制
  flow-limit:
    enable: true
    # 时间窗口周期，单位秒
    time-window: 1
    # 时间窗口周期内单一用户最多操作API
    max-access-count: 20
